# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 662be9032dd6476810693aaa4492efc5134e7f08d0d872bab1a583fb972b3e78815f4d8bccee173159617a34c813ab88300943e25d6007d3a6a66e037b7291ce

test:
  secret_key_base: efa92eedc265e8ed43e70cf64aa3a2cccb8d75ba7fb4a555a3c4b30c311085dbe0da6c1bf9597e56909beb597269e6326612264d93b650063a79e682995b8e77

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
